name: default
aliphysics: vAN-20170222-1
numevents: 50000
numbjobs: 10
gen: pythia6
proc: charm
qmass: -1
facscfact: 1
renscfact: 1
lhans: 11000
beam_type: pp
ebeam1: 3500
ebeam2: 3500
nPDFset: 3
nPDFerrSet: 1
ttl: 7200
max_files_per_job: 10
pthard: no
